import {
  type DeviceListInput,
  AuthAccessReadScope,
  AuthOrchestrationOperateScope,
  AuthOrchestrationReadScope,
  AuthRelayReadScope,
  AuthRelayWriteScope,
  AuthReviewWriteScope,
  AuthTerminalOperateScope,
  ORCHESTRATION_WS_METHODS,
  type AuthEnvironmentScope,
  WS_METHODS,
  WsRpcGroup,
} from "@t3tools/contracts";
import type * as RpcGroup from "effect/unstable/rpc/RpcGroup";

type WsRpcMethod = RpcGroup.Rpcs<typeof WsRpcGroup>["_tag"];

/**
 * Keep authorization coverage coupled to the RPC group itself. Adding an RPC to
 * `WsRpcGroup` without choosing a scope is a type error instead of a production
 * runtime failure.
 */
export const RPC_REQUIRED_SCOPES = {
  [ORCHESTRATION_WS_METHODS.dispatchCommand]: AuthOrchestrationOperateScope,
  [ORCHESTRATION_WS_METHODS.getWorkflowScript]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.getTurnDiff]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.getFullThreadDiff]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.searchThreads]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.subscribeShell]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.getArchivedShellSnapshot]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.subscribeThread]: AuthOrchestrationReadScope,
  [WS_METHODS.serverProbe]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetConfig]: AuthOrchestrationReadScope,
  [WS_METHODS.serverRefreshProviders]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateProvider]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerAuthStart]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerConsumeResetCredit]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerAuthComplete]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerAuthRespond]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerAuthCancel]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerAuthLogout]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerAuthSubscribe]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerInstallStart]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerInstallCancel]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerInstallSubscribe]: AuthOrchestrationReadScope,
  [WS_METHODS.providerInstallRemove]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateServer]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateServerWithProgress]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverCommitDesktopUpdate]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpsertKeybinding]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverRemoveKeybinding]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetSettings]: AuthOrchestrationReadScope,
  [WS_METHODS.serverUpdateSettings]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverDiscoverSourceControl]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetTraceDiagnostics]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetProcessDiagnostics]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetHostResources]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetProcessResourceHistory]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetResourceTelemetryHistory]: AuthOrchestrationReadScope,
  [WS_METHODS.serverRetryResourceTelemetry]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetUsageSummary]: AuthOrchestrationReadScope,
  [WS_METHODS.serverRefreshUsageRates]: AuthOrchestrationReadScope,
  [WS_METHODS.serverSignalProcess]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverReportClientActivity]: AuthOrchestrationReadScope,
  [WS_METHODS.serverReportHostPowerState]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetBackgroundPolicy]: AuthOrchestrationReadScope,
  [WS_METHODS.cloudGetRelayClientStatus]: AuthRelayReadScope,
  [WS_METHODS.cloudInstallRelayClient]: AuthRelayWriteScope,
  [WS_METHODS.pullRequestsList]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsListStats]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsSummary]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsRouting]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsRoutingIdentity]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsStack]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsLinkedThreads]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsDetail]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsPreview]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsActivity]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsThreadComments]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsDiffFileContents]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsFilesViewed]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsRunAction]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsUpdate]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsComment]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsUpdateComment]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsSubmitReview]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsReplyToThread]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsSetThreadResolution]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsSetReaction]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsSetFilesViewed]: AuthOrchestrationOperateScope,
  // Read scope like the reads it un-caches: refreshing is part of reading, and a read-only
  // client pressing refresh must not be told it may not look again.
  [WS_METHODS.pullRequestsInvalidate]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsSubscribeRefreshes]: AuthOrchestrationReadScope,
  // The candidate list is a read like the detail beside it; asking somebody for a review is a
  // write like every other one.
  [WS_METHODS.pullRequestsReviewerCandidates]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsRequestReviewers]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsLabelCandidates]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsSetLabels]: AuthOrchestrationOperateScope,
  [WS_METHODS.sourceControlLookupRepository]: AuthOrchestrationReadScope,
  [WS_METHODS.sourceControlCloneRepository]: AuthOrchestrationOperateScope,
  [WS_METHODS.sourceControlPublishRepository]: AuthOrchestrationOperateScope,
  [WS_METHODS.projectCloneStart]: AuthOrchestrationOperateScope,
  [WS_METHODS.projectCloneCancel]: AuthOrchestrationOperateScope,
  [WS_METHODS.projectCloneRetry]: AuthOrchestrationOperateScope,
  [WS_METHODS.subscribeProjectClones]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsListEntries]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsReadFile]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsSearchContents]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsSearchEntries]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsWriteFile]: AuthOrchestrationOperateScope,
  [WS_METHODS.shellOpenInEditor]: AuthOrchestrationOperateScope,
  [WS_METHODS.filesystemBrowse]: AuthOrchestrationReadScope,
  [WS_METHODS.agentSessionsScan]: AuthOrchestrationReadScope,
  [WS_METHODS.agentSessionsImport]: AuthOrchestrationOperateScope,
  [WS_METHODS.assetsCreateUrl]: AuthOrchestrationReadScope,
  [WS_METHODS.attachmentsCreateUploadUrl]: AuthOrchestrationOperateScope,
  [WS_METHODS.attachmentsDelete]: AuthOrchestrationOperateScope,
  [WS_METHODS.providerUploadFeedback]: AuthOrchestrationOperateScope,
  [WS_METHODS.subscribeVcsStatus]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeWorktreeSetup]: AuthOrchestrationReadScope,
  [WS_METHODS.worktreeSetupCancel]: AuthOrchestrationOperateScope,
  [WS_METHODS.subscribeResourceTelemetry]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsRefreshStatus]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsPull]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitRunStackedAction]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitResolvePullRequest]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitPreparePullRequestThread]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsListRefs]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsCreateWorktree]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsRemoveWorktree]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsCreateRef]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsSwitchRef]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsInit]: AuthOrchestrationOperateScope,
  [WS_METHODS.reviewGetDiffPreview]: AuthReviewWriteScope,
  [WS_METHODS.reviewGetDiffFileContents]: AuthReviewWriteScope,
  [WS_METHODS.terminalOpen]: AuthTerminalOperateScope,
  [WS_METHODS.terminalAttach]: AuthTerminalOperateScope,
  [WS_METHODS.terminalWrite]: AuthTerminalOperateScope,
  [WS_METHODS.terminalResize]: AuthTerminalOperateScope,
  [WS_METHODS.terminalClear]: AuthTerminalOperateScope,
  [WS_METHODS.terminalRestart]: AuthTerminalOperateScope,
  [WS_METHODS.terminalClose]: AuthTerminalOperateScope,
  [WS_METHODS.subscribeTerminalEvents]: AuthTerminalOperateScope,
  [WS_METHODS.subscribeTerminalMetadata]: AuthTerminalOperateScope,
  [WS_METHODS.previewOpen]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewNavigate]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewResize]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewRefresh]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewClose]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewList]: AuthOrchestrationReadScope,
  [WS_METHODS.previewReportStatus]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationConnect]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationRespond]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationFocusHost]: AuthOrchestrationOperateScope,
  [WS_METHODS.subscribePreviewEvents]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeDiscoveredLocalServers]: AuthOrchestrationReadScope,
  [WS_METHODS.deviceConfigure]: AuthOrchestrationOperateScope,
  [WS_METHODS.deviceTestHost]: AuthOrchestrationOperateScope,
  [WS_METHODS.deviceList]: AuthOrchestrationReadScope,
  [WS_METHODS.deviceOpen]: AuthOrchestrationOperateScope,
  [WS_METHODS.deviceClose]: AuthOrchestrationOperateScope,
  [WS_METHODS.deviceShutdown]: AuthOrchestrationOperateScope,
  [WS_METHODS.deviceDetail]: AuthOrchestrationReadScope,
  [WS_METHODS.deviceAction]: AuthOrchestrationOperateScope,
  [WS_METHODS.subscribeDeviceState]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeServerConfig]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeServerLifecycle]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeAuthAccess]: AuthAccessReadScope,
  [WS_METHODS.subscribeBackgroundPolicy]: AuthOrchestrationReadScope,
} as const satisfies Readonly<Record<WsRpcMethod, AuthEnvironmentScope>>;

export function requiredScopeForRpcMethod(method: string): AuthEnvironmentScope {
  if (!Object.hasOwn(RPC_REQUIRED_SCOPES, method)) {
    throw new Error(`RPC method ${method} has no declared authorization scope.`);
  }
  const requiredScope = RPC_REQUIRED_SCOPES[method as WsRpcMethod];
  if (requiredScope === undefined) {
    throw new Error(`RPC method ${method} has no declared authorization scope.`);
  }
  return requiredScope;
}

/** Retrying can install or restart tools even though ordinary listing is readable. */
export const requiredScopeForDeviceList = (input: DeviceListInput): AuthEnvironmentScope =>
  input.retryHostId || input.updateTool
    ? AuthOrchestrationOperateScope
    : AuthOrchestrationReadScope;

/**
 * What a thread guest (a session paired from a thread invite, carrying
 * `threadId`) may do with an RPC. Scopes still apply first; this is a
 * restriction layered on top of them.
 *
 * - `denied`: the guest gets an authorization error. The default for anything
 *   that reaches the filesystem, terminals, git, settings, other threads, or
 *   the environment as a whole.
 * - `environment`: environment-neutral and safe as-is; what a client needs to
 *   connect and render at all.
 * - `thread`: the handler must confine the call to the guest's thread itself
 *   (match the payload's thread id, or filter what it returns).
 *
 * Adding an RPC without choosing is a type error, the same guarantee the scope
 * table gives.
 */
export type ThreadGuestRpcAccess = "denied" | "environment" | "thread";

export const RPC_THREAD_GUEST_ACCESS = {
  [ORCHESTRATION_WS_METHODS.dispatchCommand]: "thread",
  [ORCHESTRATION_WS_METHODS.getWorkflowScript]: "denied",
  [ORCHESTRATION_WS_METHODS.getTurnDiff]: "thread",
  [ORCHESTRATION_WS_METHODS.getFullThreadDiff]: "thread",
  [ORCHESTRATION_WS_METHODS.searchThreads]: "denied",
  [ORCHESTRATION_WS_METHODS.subscribeShell]: "thread",
  [ORCHESTRATION_WS_METHODS.getArchivedShellSnapshot]: "denied",
  [ORCHESTRATION_WS_METHODS.subscribeThread]: "thread",
  [WS_METHODS.serverProbe]: "environment",
  [WS_METHODS.serverGetConfig]: "environment",
  [WS_METHODS.serverRefreshProviders]: "denied",
  [WS_METHODS.serverUpdateProvider]: "denied",
  [WS_METHODS.providerAuthStart]: "denied",
  [WS_METHODS.providerConsumeResetCredit]: "denied",
  [WS_METHODS.providerAuthComplete]: "denied",
  [WS_METHODS.providerAuthRespond]: "denied",
  [WS_METHODS.providerAuthCancel]: "denied",
  [WS_METHODS.providerAuthLogout]: "denied",
  [WS_METHODS.providerAuthSubscribe]: "denied",
  [WS_METHODS.providerInstallStart]: "denied",
  [WS_METHODS.providerInstallCancel]: "denied",
  [WS_METHODS.providerInstallSubscribe]: "denied",
  [WS_METHODS.providerInstallRemove]: "denied",
  [WS_METHODS.serverUpdateServer]: "denied",
  [WS_METHODS.serverUpdateServerWithProgress]: "denied",
  [WS_METHODS.serverCommitDesktopUpdate]: "denied",
  [WS_METHODS.serverUpsertKeybinding]: "denied",
  [WS_METHODS.serverRemoveKeybinding]: "denied",
  [WS_METHODS.serverGetSettings]: "denied",
  [WS_METHODS.serverUpdateSettings]: "denied",
  [WS_METHODS.serverDiscoverSourceControl]: "denied",
  [WS_METHODS.serverGetTraceDiagnostics]: "denied",
  [WS_METHODS.serverGetProcessDiagnostics]: "denied",
  [WS_METHODS.serverGetHostResources]: "denied",
  [WS_METHODS.serverGetProcessResourceHistory]: "denied",
  [WS_METHODS.serverGetResourceTelemetryHistory]: "denied",
  [WS_METHODS.serverRetryResourceTelemetry]: "denied",
  [WS_METHODS.serverGetUsageSummary]: "denied",
  [WS_METHODS.serverRefreshUsageRates]: "denied",
  [WS_METHODS.serverSignalProcess]: "denied",
  [WS_METHODS.serverReportClientActivity]: "environment",
  [WS_METHODS.serverReportHostPowerState]: "denied",
  [WS_METHODS.serverGetBackgroundPolicy]: "environment",
  [WS_METHODS.cloudGetRelayClientStatus]: "denied",
  [WS_METHODS.cloudInstallRelayClient]: "denied",
  [WS_METHODS.pullRequestsList]: "denied",
  [WS_METHODS.pullRequestsListStats]: "denied",
  [WS_METHODS.pullRequestsSummary]: "denied",
  [WS_METHODS.pullRequestsRouting]: "denied",
  [WS_METHODS.pullRequestsRoutingIdentity]: "denied",
  [WS_METHODS.pullRequestsStack]: "denied",
  [WS_METHODS.pullRequestsLinkedThreads]: "denied",
  [WS_METHODS.pullRequestsDetail]: "denied",
  [WS_METHODS.pullRequestsPreview]: "denied",
  [WS_METHODS.pullRequestsActivity]: "denied",
  [WS_METHODS.pullRequestsThreadComments]: "denied",
  [WS_METHODS.pullRequestsDiffFileContents]: "denied",
  [WS_METHODS.pullRequestsFilesViewed]: "denied",
  [WS_METHODS.pullRequestsRunAction]: "denied",
  [WS_METHODS.pullRequestsUpdate]: "denied",
  [WS_METHODS.pullRequestsComment]: "denied",
  [WS_METHODS.pullRequestsUpdateComment]: "denied",
  [WS_METHODS.pullRequestsSubmitReview]: "denied",
  [WS_METHODS.pullRequestsReplyToThread]: "denied",
  [WS_METHODS.pullRequestsSetThreadResolution]: "denied",
  [WS_METHODS.pullRequestsSetReaction]: "denied",
  [WS_METHODS.pullRequestsSetFilesViewed]: "denied",
  [WS_METHODS.pullRequestsInvalidate]: "denied",
  [WS_METHODS.pullRequestsSubscribeRefreshes]: "denied",
  [WS_METHODS.pullRequestsReviewerCandidates]: "denied",
  [WS_METHODS.pullRequestsRequestReviewers]: "denied",
  [WS_METHODS.pullRequestsLabelCandidates]: "denied",
  [WS_METHODS.pullRequestsSetLabels]: "denied",
  [WS_METHODS.sourceControlLookupRepository]: "denied",
  [WS_METHODS.sourceControlCloneRepository]: "denied",
  [WS_METHODS.sourceControlPublishRepository]: "denied",
  [WS_METHODS.projectCloneStart]: "denied",
  [WS_METHODS.projectCloneCancel]: "denied",
  [WS_METHODS.projectCloneRetry]: "denied",
  [WS_METHODS.subscribeProjectClones]: "denied",
  [WS_METHODS.projectsListEntries]: "denied",
  [WS_METHODS.projectsReadFile]: "denied",
  [WS_METHODS.projectsSearchContents]: "denied",
  [WS_METHODS.projectsSearchEntries]: "denied",
  [WS_METHODS.projectsWriteFile]: "denied",
  [WS_METHODS.shellOpenInEditor]: "denied",
  [WS_METHODS.filesystemBrowse]: "denied",
  [WS_METHODS.agentSessionsScan]: "denied",
  [WS_METHODS.agentSessionsImport]: "denied",
  [WS_METHODS.assetsCreateUrl]: "thread",
  // An upload is a pending blob addressed by an unguessable id; it only joins
  // a thread through a dispatched command, which is gated to the guest's own.
  [WS_METHODS.attachmentsCreateUploadUrl]: "environment",
  [WS_METHODS.attachmentsDelete]: "environment",
  [WS_METHODS.providerUploadFeedback]: "denied",
  [WS_METHODS.subscribeVcsStatus]: "denied",
  [WS_METHODS.subscribeWorktreeSetup]: "thread",
  [WS_METHODS.worktreeSetupCancel]: "denied",
  [WS_METHODS.subscribeResourceTelemetry]: "denied",
  [WS_METHODS.vcsRefreshStatus]: "denied",
  [WS_METHODS.vcsPull]: "denied",
  [WS_METHODS.gitRunStackedAction]: "denied",
  [WS_METHODS.gitResolvePullRequest]: "denied",
  [WS_METHODS.gitPreparePullRequestThread]: "denied",
  [WS_METHODS.vcsListRefs]: "denied",
  [WS_METHODS.vcsCreateWorktree]: "denied",
  [WS_METHODS.vcsRemoveWorktree]: "denied",
  [WS_METHODS.vcsCreateRef]: "denied",
  [WS_METHODS.vcsSwitchRef]: "denied",
  [WS_METHODS.vcsInit]: "denied",
  [WS_METHODS.reviewGetDiffPreview]: "denied",
  [WS_METHODS.reviewGetDiffFileContents]: "denied",
  [WS_METHODS.terminalOpen]: "denied",
  [WS_METHODS.terminalAttach]: "denied",
  [WS_METHODS.terminalWrite]: "denied",
  [WS_METHODS.terminalResize]: "denied",
  [WS_METHODS.terminalClear]: "denied",
  [WS_METHODS.terminalRestart]: "denied",
  [WS_METHODS.terminalClose]: "denied",
  [WS_METHODS.subscribeTerminalEvents]: "denied",
  [WS_METHODS.subscribeTerminalMetadata]: "denied",
  [WS_METHODS.previewOpen]: "denied",
  [WS_METHODS.previewNavigate]: "denied",
  [WS_METHODS.previewResize]: "denied",
  [WS_METHODS.previewRefresh]: "denied",
  [WS_METHODS.previewClose]: "denied",
  [WS_METHODS.previewList]: "denied",
  [WS_METHODS.previewReportStatus]: "denied",
  [WS_METHODS.previewAutomationConnect]: "denied",
  [WS_METHODS.previewAutomationRespond]: "denied",
  [WS_METHODS.previewAutomationFocusHost]: "denied",
  [WS_METHODS.subscribePreviewEvents]: "denied",
  [WS_METHODS.subscribeDiscoveredLocalServers]: "denied",
  [WS_METHODS.deviceConfigure]: "denied",
  [WS_METHODS.deviceTestHost]: "denied",
  [WS_METHODS.deviceList]: "denied",
  [WS_METHODS.deviceOpen]: "denied",
  [WS_METHODS.deviceClose]: "denied",
  [WS_METHODS.deviceShutdown]: "denied",
  [WS_METHODS.deviceDetail]: "denied",
  [WS_METHODS.deviceAction]: "denied",
  [WS_METHODS.subscribeDeviceState]: "denied",
  [WS_METHODS.subscribeServerConfig]: "environment",
  [WS_METHODS.subscribeServerLifecycle]: "environment",
  [WS_METHODS.subscribeAuthAccess]: "denied",
  [WS_METHODS.subscribeBackgroundPolicy]: "environment",
} as const satisfies Readonly<Record<WsRpcMethod, ThreadGuestRpcAccess>>;

export function threadGuestAccessForRpcMethod(method: string): ThreadGuestRpcAccess {
  if (!Object.hasOwn(RPC_THREAD_GUEST_ACCESS, method)) {
    throw new Error(`RPC method ${method} has no declared thread guest access.`);
  }
  return RPC_THREAD_GUEST_ACCESS[method as WsRpcMethod];
}

/**
 * Commands a thread guest may dispatch at their own thread: conversation only.
 * Anything that changes the thread's lifecycle, mode, history, or worktree
 * stays with the owner.
 */
export const THREAD_GUEST_COMMAND_TYPES: ReadonlySet<string> = new Set([
  "thread.turn.start",
  "thread.turn.interrupt",
  "thread.message.user.append",
  "thread.approval.respond",
  "thread.user-input.respond",
  "thread.user-input.dismiss",
]);
